# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
    paths: 
      - '**.py'
  pull_request:
    paths: 
      - '**.py'
  workflow_dispatch:
    paths: 
      - '**.py'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.6.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        pip install pylint
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 79 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=79 --statistics
    - name: Lint with Pylint
      run: |
        pylint `find $directory -type d \( -path ./custom_env -o -path ./.vscode \) -prune -false -o -name '*.py'`
